namespace Users.Domain;

/// <summary>Identity of a <see cref="User"/>. Generated by the domain, so a user has its id before it is persisted.</summary>
internal readonly record struct UserId(Guid Value)
{
    public static UserId New() => new(Guid.NewGuid());

    public override string ToString() => Value.ToString();
}
