namespace WorkItems.Domain;

/// <summary>Identity of a <see cref="WorkItem"/>. Generated by the domain, so a work item has its id before it is persisted.</summary>
internal readonly record struct WorkItemId(Guid Value)
{
    public static WorkItemId New() => new(Guid.NewGuid());

    public override string ToString() => Value.ToString();
}
